import numpy as np

# Physical properties
MOTHER_RADIUS = 2.34529  # um
MOTHER_SURFACE_AREA = np.pi * 4.0 * (MOTHER_RADIUS**2)  # um2
MOTHER_VOLUME = np.pi * (4.0/3.0) * (MOTHER_RADIUS**3)  # um3


PARTICLE_RADIUS = 0.3072244  # um
PARTICLE_VOLUME = (4.0/3.0) * np.pi * (PARTICLE_RADIUS**3)
# PARTICLE_SURFACE_AREA = 4.0 * np.pi * (PARTICLE_RADIUS**2)
# print(f"Particle 3D surface area :\t{PARTICLE_SURFACE_AREA}")
PARTICLE_CROSSAREA = np.pi * (PARTICLE_RADIUS**2)
# print(f"Particle 2D Cross area :\t{PARTICLE_CROSSAREA}")

N_PARTICLES = 54

MOTHER_BOX_SIDELENGTH = np.sqrt(MOTHER_SURFACE_AREA)  # um

MOTHER_MITO_VOL_PERCENT = (N_PARTICLES*PARTICLE_VOLUME)/MOTHER_VOLUME  # %
MOTHER_MITO_TOTAL_VOL = MOTHER_MITO_VOL_PERCENT * MOTHER_VOLUME  # um3

# Aggregate percent
AGGREGATE_PERCENT = 0.1223005


# Resolution Thresholds
DIFFERENCE_EPSILON = 0.00001  # um
FUSION_EPSILON = PARTICLE_RADIUS  # um
FISSION_EPSILON = PARTICLE_RADIUS  # um
